---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gnomad-api
  labels:
    state: serving
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gnomad-api
  template:
    metadata:
      labels:
        name: gnomad-api
    spec:
      containers:
      - name: gnomad-api-pod
        image: gcr.io/exac-gnomad/gnomad-api
        env:
        - name: DEPLOYMENT_ENV
          value: production
        - name: GRAPHQL_PORT
          value: '80'
        - name: GNOMAD_MONGO_URL
          value: mongodb://gnomad-mongo:27017/exac
        - name: ELASTICSEARCH_URL
          value: 10.4.0.13:9200
        - name: NODE_ENV
          value: production
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      nodeSelector:
        cloud.google.com/gke-nodepool: "redis"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
