apiVersion: v1
kind: Service
metadata:
  name: gnomad-elasticsearch-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 192.168.255.0/24 # Matches IP range for Dataproc subnet
  ports:
    - name: http
      port: 9200
      protocol: TCP
  selector:
    # https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-traffic-splitting.html
    elasticsearch.k8s.elastic.co/cluster-name: "gnomad" # Matches cluster name in elasticsearch.yaml
    elasticsearch.k8s.elastic.co/node-master: "false"
